---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/elvinotan/config

server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,refresh